// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1DB0XSebDlM7yiv7wl-vVyQslkpY5kM',
    appId: '1:905953058826:web:53dc8a2b7dc31372e8bff3',
    messagingSenderId: '905953058826',
    projectId: 'to-do-list-ae1d3',
    authDomain: 'to-do-list-ae1d3.firebaseapp.com',
    storageBucket: 'to-do-list-ae1d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL4aTIP4AgnEpMLnYWRR8NK5PjzCTblDI',
    appId: '1:905953058826:android:d01fbd69eb2291e4e8bff3',
    messagingSenderId: '905953058826',
    projectId: 'to-do-list-ae1d3',
    storageBucket: 'to-do-list-ae1d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ORnPKr0_epG1CVXjx0C_i0puzZdOfFs',
    appId: '1:905953058826:ios:bcd19e7d76afbadee8bff3',
    messagingSenderId: '905953058826',
    projectId: 'to-do-list-ae1d3',
    storageBucket: 'to-do-list-ae1d3.firebasestorage.app',
    iosBundleId: 'com.example.applicationTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ORnPKr0_epG1CVXjx0C_i0puzZdOfFs',
    appId: '1:905953058826:ios:bcd19e7d76afbadee8bff3',
    messagingSenderId: '905953058826',
    projectId: 'to-do-list-ae1d3',
    storageBucket: 'to-do-list-ae1d3.firebasestorage.app',
    iosBundleId: 'com.example.applicationTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE1DB0XSebDlM7yiv7wl-vVyQslkpY5kM',
    appId: '1:905953058826:web:aa52b0473cf70370e8bff3',
    messagingSenderId: '905953058826',
    projectId: 'to-do-list-ae1d3',
    authDomain: 'to-do-list-ae1d3.firebaseapp.com',
    storageBucket: 'to-do-list-ae1d3.firebasestorage.app',
  );

}